;;; doom-wallust-theme.el --- generated by wallust -*- no-byte-compile: t; -*-
(require 'doom-themes)

(defgroup doom-wallust-theme nil
  "Options for the `doom-wallust' theme."
  :group 'doom-themes)

(def-doom-theme doom-wallust
    "A theme generated live from wallust."

  ((bg         '("{{background}}" nil nil))
   (fg         '("{{foreground}}" nil nil))
   (bg-alt     (doom-darken bg 0.15))
   (fg-alt     (doom-blend fg bg 0.7))

   (base0      (doom-darken bg 0.3))
   (base1      (doom-darken bg 0.15))
   (base2      (doom-darken bg 0.05))
   (base3      bg)
   (base4      (doom-blend fg bg 0.3))
   (base5      (doom-blend fg bg 0.5))
   (base6      (doom-blend fg bg 0.7))
   (base7      (doom-blend fg bg 0.85))
   (base8      fg)

   (grey       base4)
   (red        '("{{color1}}" nil nil))
   (orange     '("{{color3}}" nil nil))
   (green      '("{{color2}}" nil nil))
   (teal       '("{{color6}}" nil nil))
   (yellow     '("{{color3}}" nil nil))
   (blue       '("{{color4}}" nil nil))
   (dark-blue  (doom-darken blue 0.2))
   (magenta    '("{{color5}}" nil nil))
   (violet     '("{{color5}}" nil nil))
   (cyan       '("{{color6}}" nil nil))
   (dark-cyan  (doom-darken cyan 0.2))

   (highlight      blue)
   (vertical-bar   base0)
   (selection      dark-blue)
   (builtin        magenta)
   (comments       base5)
   (doc-comments   (doom-lighten base5 0.25))
   (constants      violet)
   (functions      magenta)
   (keywords       red)
   (methods        cyan)
   (operators      blue)
   (type           yellow)
   (strings        green)
   (variables      violet)
   (numbers        orange)
   (region         (doom-blend blue bg 0.55))
   (error          red)
   (warning        yellow)
   (success        green)
   (vc-modified    orange)
   (vc-added       green)
   (vc-deleted     red)

   (modeline-fg          fg)
   (modeline-fg-alt      base5)
   (modeline-bg          base0)
   (modeline-bg-inactive base0))

  ;; --- extra face overrides
  ((link      :foreground blue :underline t)
   (button    :foreground blue)
   (highlight :foreground base8 :background selection)
   (tooltip   :background base1 :foreground fg)
   (region    :background (doom-blend blue bg 0.55) :distant-foreground fg)
   (hl-line   :background (doom-blend blue bg 0.15))))

(provide-theme 'doom-wallust)
