add_newline = true

format = '''[ $username@$hostname ](bg:{{color4}} fg:{{color0}} bold) [$directory](bold {{color6}})$git_branch$git_status$nodejs$rust$python$golang$c$character'''

right_format = '''[$time](bold {{color5}})'''

[username]
show_always = true
format = '$user'
style_user = 'bg:{{color4}} fg:{{color0}} bold'
style_root = 'bg:{{color1}} fg:{{color0}} bold'

[hostname]
ssh_only = false
format = '$hostname'
style = 'bg:{{color4}} fg:{{color0}} bold'

[directory]
format = '[$path]($style) '
truncation_length = 3
truncate_to_repo = true
read_only = '[RO]'
style = 'bold {{color6}}'

[character]
success_symbol = '[_](bold {{color2}})'
error_symbol   = '[X](bold {{color1}})'
vimcmd_symbol  = '[<](bold {{color2}})'

[git_branch]
symbol = ''
style = 'bold {{color3}}'
format = '[\[$branch\]]($style) '

[git_status]
style = 'bold {{color1}}'
format = '[\[$all_status$ahead_behind\]]($style) '

[nodejs]
symbol = 'JS'
style = 'bold {{color2}}'
format = '[\[$symbol:$version\]]($style) '

[rust]
symbol = 'RS'
style = 'bold {{color3}}'
format = '[\[$symbol:$version\]]($style) '

[python]
symbol = 'PY'
style = 'bold {{color4}}'
format = '[\[$symbol:$version\]]($style) '

[golang]
symbol = 'GO'
style = 'bold {{color6}}'
format = '[\[$symbol:$version\]]($style) '

[c]
symbol = 'C'
style = 'bold {{color5}}'
format = '[\[$symbol:$version\]]($style) '

[fill]
disabled = true

[time]
disabled = false
format = '[$time]($style)'
style = 'bold {{color5}}'