#!/usr/bin/env python3
"""Validate and apply only the shell's owned shortcuts. Preview saves privately."""
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile

CATALOG = [
    ("launcher", "App library", "space"),
    ("wallpaper", "Wallpaper studio", "SHIFT + W"),
    ("quickwallpaper", "Quick wallpapers", "CTRL + W"),
    ("workspaces", "Workspace manager", "CTRL + E"),
    ("settings", "Settings", "CTRL + comma"),
    ("wellbeing", "Your day", "CTRL + C"),
    ("power", "Power drawer", "CTRL + P"),
]
MODS = {"SHIFT": 1, "CTRL": 4, "ALT": 8, "MOD2": 16, "MOD3": 32, "SUPER": 64, "MOD5": 128}
ALIASES = {"CONTROL": "CTRL", "WIN": "SUPER", "META": "SUPER"}
KEYS = {"SPACE": "space", "ENTER": "Return", "RETURN": "Return", "ESC": "Escape", "ESCAPE": "Escape", "COMMA": "comma", "TAB": "Tab", "BACKSPACE": "BackSpace", "DELETE": "Delete", "LEFT": "Left", "RIGHT": "Right", "UP": "Up", "DOWN": "Down", "HOME": "Home", "END": "End", "PAGEUP": "Prior", "PAGEDOWN": "Next"}
HEADER = "-- pixel-shell-keybindings: "


def defaults():
    return {"shared": "ALT", "actions": {key: {"shared": True, "enabled": True, "key": chord} for key, _, chord in CATALOG}}


def modifiers(text):
    if not isinstance(text, str) or len(text) > 100:
        raise ValueError("Invalid shared modifier")
    parts = [ALIASES.get(p.strip().upper(), p.strip().upper()) for p in text.split("+")] if text.strip() else []
    if any(p not in MODS for p in parts):
        raise ValueError("Use SUPER, ALT, CTRL, SHIFT, MOD2, MOD3 or MOD5 as modifiers")
    return " + ".join(m for m in MODS if m in parts)


def chord(text):
    if not isinstance(text, str) or len(text) > 150:
        raise ValueError("Invalid shortcut")
    parts = text.split("+")
    key = parts.pop().strip()
    if not re.fullmatch(r"[A-Za-z0-9_]+|code:[0-9]{1,3}", key) or key.upper() in MODS or key.upper() in ALIASES:
        raise ValueError("Use one key name (F8, comma, space, code:38…) after any modifiers")
    if key.startswith("code:") and not 8 <= int(key[5:]) <= 255:
        raise ValueError("Keycodes must be between 8 and 255")
    key = KEYS.get(key.upper(), key.upper() if len(key) == 1 else key)
    if re.fullmatch(r"f[0-9]{1,2}", key, re.I):
        key = key.upper()
    prefix = modifiers("+".join(parts))
    return prefix + " + " + key if prefix else key


def validate(raw):
    if not isinstance(raw, dict) or set(raw) != {"shared", "actions"}:
        raise ValueError("Invalid shortcut configuration")
    actions = raw["actions"]
    if not isinstance(actions, dict) or set(actions) != {x[0] for x in CATALOG}:
        raise ValueError("Shortcut actions are incomplete or unknown")
    result = {"shared": modifiers(raw["shared"]), "actions": {}}
    occupied = {}
    for key, label, _ in CATALOG:
        item = actions[key]
        if not isinstance(item, dict) or set(item) != {"shared", "enabled", "key"} or any(type(item[k]) is not bool for k in ("shared", "enabled")):
            raise ValueError("Invalid shortcut for " + label)
        try:
            item = {**item, "key": chord(item["key"])}
        except ValueError as error:
            raise ValueError(label + ": " + str(error)) from error
        result["actions"][key] = item
        full = effective(result, key)
        if item["enabled"]:
            if full.lower() in occupied:
                raise ValueError("Duplicate shortcut: " + label + " and " + occupied[full.lower()] + " use " + full)
            prefix, _, key_name = full.lower().rpartition(" + ")
            for previous in occupied:
                other_prefix, _, other_key = previous.rpartition(" + ")
                if prefix == other_prefix and key_name.startswith("code:") != other_key.startswith("code:"):
                    raise ValueError("Use key names consistently for shortcuts sharing a modifier; keycode equivalence depends on your layout")
            occupied[full.lower()] = label
    return result


def effective(config, key):
    item = config["actions"][key]
    return chord((config["shared"] + " + " if item["shared"] and config["shared"] else "") + item["key"])


def rows(config):
    return [{"id": key, "chord": effective(config, key)} for key, _, _ in CATALOG if config["actions"][key]["enabled"]]


def lua_rows(config):
    return "{" + ",".join('{id=' + json.dumps(r['id']) + ',chord=' + json.dumps(r['chord']) + '}' for r in rows(config)) + "}"


def render(config):
    return HEADER + json.dumps(config, separators=(",", ":")) + "\n-- Generated by Settings / Keys. No commands from user input.\nreturn " + lua_rows(config) + "\n"


def config_path():
    return Path((os.environ.get("XDG_CONFIG_HOME") or str(Path.home() / ".config"))) / "pixel-shell/keybindings.lua"


def read_config(path):
    if not path.exists():
        return validate(defaults())
    text = path.read_text()
    if not text.startswith(HEADER):
        raise ValueError("Unrecognized keybindings file; back it up before replacing it with Defaults")
    config = validate(json.loads(text.splitlines()[0][len(HEADER):]))
    if text != render(config):
        raise ValueError("Keybindings file was edited externally; back it up before replacing it with Defaults")
    return config


def atomic_write(path, text):
    if path.is_symlink():
        raise ValueError("keybindings.lua is managed by a symlink; edit its source instead")
    path.parent.mkdir(parents=True, exist_ok=True)
    name = None
    try:
        with tempfile.NamedTemporaryFile(mode="w", dir=path.parent, delete=False) as f:
            name = f.name
            f.write(text)
            f.flush()
            os.fsync(f.fileno())
        os.replace(name, path)
    finally:
        if name and os.path.exists(name):
            os.unlink(name)


def hypr(args):
    p = subprocess.run(["hyprctl", *args], text=True, capture_output=True, timeout=5)
    if p.returncode:
        raise RuntimeError(p.stderr.strip() or p.stdout.strip() or "Hyprland request failed")
    return p.stdout.strip()


def evaluate(code):
    result = hypr(["eval", code])
    if result.lower() != "ok":
        raise RuntimeError(result or "Hyprland did not acknowledge the change")


def check_conflicts(config, binds):
    if not isinstance(binds, list) or any(
        not isinstance(b, dict) or type(b.get("modmask")) is not int
        or not isinstance(b.get("key", ""), str) or type(b.get("keycode", 0)) is not int
        or not isinstance(b.get("description", ""), str) for b in binds
    ):
        raise ValueError("Could not read current compositor bindings")
    for row in rows(config):
        parts = row["chord"].split(" + ")
        mask = sum(MODS[m] for m in parts[:-1])
        key = parts[-1]
        for bind in binds:
            if bind.get("description", "").startswith("Pixel shell: ") or (bind.get("submap") and bind.get("submap_universal") not in (True, "true")):
                continue
            same_key = (str(bind.get("keycode")) == key[5:] if key.startswith("code:") else str(bind.get("key", "")).lower() == key.lower())
            # Keycode/keysym equivalence depends on the user's keyboard layout.
            # Refuse ambiguous same-modifier cases rather than claiming them safe.
            ambiguous = bool(bind.get("keycode")) != key.startswith("code:")
            if bind.get("modmask") == mask and ambiguous:
                raise ValueError("Cannot safely compare keycodes with key names for " + row["chord"] + ". Use a key name or a different modifier.")
            if bind.get("modmask") == mask and (same_key or bind.get("catch_all")):
                raise ValueError(row["chord"] + " is already used by another compositor shortcut. Choose a different key; nothing was changed.")


def apply(config, path, preview):
    if preview:
        atomic_write(path, render(config))
        return "Saved in this preview only. Live keybindings were not changed."
    evaluate('assert(_G.pixel_shell_keys and _G.pixel_shell_keys.version == 1, "Activate the updated Hyprland configuration first; no bindings changed")')
    check_conflicts(config, json.loads(hypr(["-j", "binds"])))
    try:
        evaluate("pixel_shell_keys.apply(" + lua_rows(config) + ")")
        atomic_write(path, render(config))
    except (OSError, ValueError, RuntimeError, subprocess.SubprocessError) as error:
        try:
            evaluate("pixel_shell_keys.undo()")
        except (OSError, RuntimeError, subprocess.SubprocessError) as rollback:
            raise RuntimeError(f"{error}. Restoration could not be confirmed: {rollback}. Reload your Hyprland configuration to restore saved shortcuts.") from error
        raise
    return "Saved and applied. Only shell shortcuts changed."


def main():
    try:
        action = sys.argv[1]
        if action in ("read", "defaults"):
            config = read_config(config_path()) if action == "read" else validate(defaults())
            message = ""
        elif action == "apply":
            config = validate(json.loads(sys.argv[2]))
            message = apply(config, config_path(), os.environ.get("PIXEL_SHELL_PREVIEW") == "1")
        else:
            raise ValueError("Unknown shortcut operation")
        print(json.dumps({"config": config, "catalog": [{"id": k, "label": label} for k, label, _ in CATALOG], "message": message}))
        return 0
    except (IndexError, OSError, ValueError, RuntimeError, subprocess.SubprocessError) as error:
        print(str(error), file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
